linters:
  disable:
    # Disable errcheck for now - too many false positives in test setup code
    # These should be fixed in a future refactor
    - errcheck

linters-settings:
  govet:
    disable:
      # fieldalignment is too strict for this codebase
      - fieldalignment
      # shadow is too strict for error handling patterns
      - shadow

run:
  timeout: 5m
