package ytsync

import (
	"context"
	"errors"
	"fmt"
	"log"
	"testing"
)

// ExampleListVideos demonstrates how to list videos from a YouTube channel.
func ExampleListVideos() {
	ctx := context.Background()

	// List videos from a channel using RSS (fast, recent videos)
	videos, err := ListVideos(ctx, "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw")
	if err != nil {
		log.Printf("Error listing videos: %v\n", err)
		return
	}

	// Print first 5 videos
	for i, v := range videos {
		if i >= 5 {
			break
		}
		fmt.Printf("%d. %s (%s)\n", i+1, v.Title, v.ID)
	}
}

// ExampleListVideosWithOptions demonstrates configurable video listing.
func ExampleListVideosWithOptions() {
	ctx := context.Background()

	// List with options: use yt-dlp for full history, limit to 50 results
	videos, err := ListVideosWithOptions(ctx, "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw", &ListOptions{
		MaxResults: 50,
		UseRSS:     false, // Use yt-dlp for full history
	})
	if err != nil {
		log.Printf("Error listing videos: %v\n", err)
		return
	}

	fmt.Printf("Found %d videos\n", len(videos))
}

// ExampleExtractTranscript demonstrates how to extract a transcript.
func ExampleExtractTranscript() {
	ctx := context.Background()

	// Extract English transcript for a video
	transcript, err := ExtractTranscript(ctx, "dQw4w9WgXcQ")
	if err != nil {
		log.Printf("Error extracting transcript: %v\n", err)
		return
	}

	fmt.Printf("Language: %s\n", transcript.Language)
	fmt.Printf("Auto-generated: %v\n", transcript.IsAutoGenerated)
	fmt.Printf("Entries: %d\n", len(transcript.Entries))

	// Print first 3 entries
	for i, entry := range transcript.Entries {
		if i >= 3 {
			break
		}
		fmt.Printf("[%.2fs] %s\n", entry.Start, entry.Text)
	}
}

// ExampleExtractTranscriptWithOptions demonstrates configurable transcript extraction.
func ExampleExtractTranscriptWithOptions() {
	ctx := context.Background()

	// Extract transcript with specific options
	transcript, err := ExtractTranscriptWithOptions(ctx, "dQw4w9WgXcQ", &TranscriptOptions{
		Languages:         []string{"en", "es"}, // Try English first, then Spanish
		SkipAutoGenerated: true,                 // Skip auto-generated captions
	})
	if err != nil {
		log.Printf("Error extracting transcript: %v\n", err)
		return
	}

	fmt.Printf("Language: %s (%s)\n", transcript.Language, transcript.LanguageName)
	fmt.Printf("Source: %s\n", transcript.VideoID)
}

// ExampleFetchVideoMetadata demonstrates how to get comprehensive video metadata.
func ExampleFetchVideoMetadata() {
	ctx := context.Background()

	// Fetch comprehensive metadata
	metadata, err := FetchVideoMetadata(ctx, "dQw4w9WgXcQ")
	if err != nil {
		log.Printf("Error fetching metadata: %v\n", err)
		return
	}

	fmt.Printf("Title: %s\n", metadata.Title)
	fmt.Printf("Duration: %d seconds\n", metadata.Duration)
	fmt.Printf("Views: %d\n", metadata.ViewCount)
	fmt.Printf("Channel: %s\n", metadata.Uploader)
	fmt.Printf("Upload Date: %s\n", metadata.UploadDate)

	if len(metadata.Categories) > 0 {
		fmt.Printf("Categories: %v\n", metadata.Categories)
	}
}

// TestErrorHandling demonstrates error handling patterns.
func TestErrorHandling(t *testing.T) {
	ctx := context.Background()

	// Demonstrate error handling
	_, err := ListVideos(ctx, "invalid-url")
	if err != nil {
		// Check for specific sentinel errors
		if errors.Is(err, ErrInvalidURL) {
			t.Log("The provided URL is invalid")
		}
		if errors.Is(err, ErrChannelNotFound) {
			t.Log("The channel was not found")
		}
		if errors.Is(err, ErrRateLimited) {
			t.Log("Rate limited, please try again later")
		}

		// Extract wrapped error details
		var listerErr *ListerError
		if errors.As(err, &listerErr) {
			t.Logf("Listing failed for %s: %v\n", listerErr.Channel, listerErr.Err)
		}
	}
}
