// Package ytsync provides a high-level API for YouTube video synchronization.
//
// This package offers convenience functions for the most common operations:
// listing videos, downloading videos, and extracting transcripts.
//
// Example usage:
//
//	ctx := context.Background()
//	videos, err := ytsync.ListVideos(ctx, "https://www.youtube.com/channel/UCxxxxx")
//	if err != nil {
//		log.Fatal(err)
//	}
//	for _, v := range videos {
//		fmt.Println(v.Title)
//	}
package ytsync

import (
	"context"
	"fmt"
	"ytsync/config"
	"ytsync/storage"
	"ytsync/youtube"
)

// ListVideos retrieves videos from a YouTube channel using default configuration.
// It uses the RSS feed by default for fast listing of recent videos.
//
// The channelURL can be:
// - A channel URL: https://www.youtube.com/channel/UCxxxxx
// - A handle: https://www.youtube.com/@channelname
// - A channel ID: UCxxxxx
//
// For full history of all videos, use ListVideosWithOptions with a Ytdlp lister.
func ListVideos(ctx context.Context, channelURL string) ([]youtube.VideoInfo, error) {
	return ListVideosWithOptions(ctx, channelURL, &ListOptions{})
}

// ListOptions configures video listing behavior.
type ListOptions struct {
	// MaxResults limits the number of videos to retrieve (0 = all available)
	MaxResults int
	// UseRSS forces using RSS feed instead of yt-dlp (default: true for efficiency)
	UseRSS bool
	// UseYouTubeAPI forces using YouTube Data API v3 if enabled in config (default: false)
	UseYouTubeAPI bool
	// ContentType specifies what to list: videos, streams, or both (default: videos)
	ContentType youtube.ContentType
}

// ListVideosWithOptions retrieves videos with custom options.
func ListVideosWithOptions(ctx context.Context, channelURL string, opts *ListOptions) ([]youtube.VideoInfo, error) {
	if opts == nil {
		opts = &ListOptions{}
	}

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Create lister
	var lister youtube.VideoLister
	if opts.UseYouTubeAPI && cfg.YouTubeAPIEnabled {
		if cfg.YouTubeAPIKey == "" {
			return nil, fmt.Errorf("YouTube API requested but no API key configured")
		}
		apiLister, err := youtube.NewAPILister(cfg.YouTubeAPIKey, cfg.YouTubeAPIQuotaReserve)
		if err != nil {
			return nil, fmt.Errorf("create api lister: %w", err)
		}
		// Set up fallback to yt-dlp when quota exhausted
		ytdlp := youtube.NewYtdlpLister()
		ytdlp.Path = cfg.YtdlpPath
		ytdlp.Timeout = cfg.YtdlpTimeout
		apiLister.SetFallbackLister(ytdlp)
		lister = apiLister
	} else if opts.UseRSS {
		lister = youtube.NewRSSLister()
	} else {
		ytdlp := youtube.NewYtdlpLister()
		ytdlp.Path = cfg.YtdlpPath
		ytdlp.Timeout = cfg.YtdlpTimeout
		lister = ytdlp
	}

	// Build list options
	listOpts := &youtube.ListOptions{
		MaxResults:  opts.MaxResults,
		ContentType: opts.ContentType,
	}

	// List videos
	videos, err := lister.ListVideos(ctx, channelURL, listOpts)
	if err != nil {
		return nil, fmt.Errorf("list videos: %w", err)
	}

	return videos, nil
}

// TranscriptOptions configures transcript extraction.
type TranscriptOptions struct {
	// Languages specifies preferred language codes (e.g., ["en", "es"]).
	// Empty means try all available languages.
	Languages []string
	// SkipAutoGenerated skips auto-generated captions if true.
	SkipAutoGenerated bool
}

// ExtractTranscript retrieves and parses the transcript for a video.
// It returns the first available transcript matching the options.
func ExtractTranscript(ctx context.Context, videoID string) (*youtube.Transcript, error) {
	return ExtractTranscriptWithOptions(ctx, videoID, &TranscriptOptions{})
}

// ExtractTranscriptWithOptions extracts a transcript with custom options.
func ExtractTranscriptWithOptions(ctx context.Context, videoID string, opts *TranscriptOptions) (*youtube.Transcript, error) {
	if opts == nil {
		opts = &TranscriptOptions{}
	}

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Create extractor
	extractor := youtube.NewTranscriptExtractor()
	extractor.YtdlpPath = cfg.YtdlpPath
	extractor.Timeout = cfg.YtdlpTimeout

	// Build extract options
	extractOpts := &youtube.ExtractOptions{
		Languages:         opts.Languages,
		Format:            "json3",
		SkipAutoGenerated: opts.SkipAutoGenerated,
	}

	// Extract transcript
	transcript, err := extractor.Extract(ctx, videoID, extractOpts)
	if err != nil {
		return nil, fmt.Errorf("extract transcript: %w", err)
	}

	return transcript, nil
}

// FetchVideoMetadata retrieves comprehensive metadata for a video using yt-dlp.
// This includes title, description, duration, view count, and other details.
func FetchVideoMetadata(ctx context.Context, videoID string) (*youtube.VideoMetadata, error) {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Fetch metadata
	metadata, err := youtube.FetchMetadata(ctx, videoID, cfg.YtdlpPath)
	if err != nil {
		return nil, fmt.Errorf("fetch metadata: %w", err)
	}

	return metadata, nil
}

// SyncOptions configures video synchronization behavior.
type SyncOptions struct {
	// MaxResults limits the number of videos to retrieve (0 = all available)
	MaxResults int
	// ContentType specifies what to list: videos, streams, or both
	ContentType youtube.ContentType
	// StorePath is the path to the JSON store for persisting sync state
	// Required for incremental sync functionality
	StorePath string
}

// SyncChannelVideos performs an efficient incremental sync of channel videos.
// It uses the sync manager to coordinate between RSS (fast, incremental) and
// full sync strategies. Sync state is persisted to enable gap detection and
// resumable pagination.
//
// Returns a SyncResult containing the videos discovered and metadata about the sync.
func SyncChannelVideos(ctx context.Context, channelURL string, opts *SyncOptions) (*SyncResult, error) {
	if opts == nil {
		opts = &SyncOptions{}
	}

	if opts.StorePath == "" {
		return nil, fmt.Errorf("StorePath is required for sync operations")
	}

	// Initialize storage
	store, err := storage.NewJSONStore(opts.StorePath)
	if err != nil {
		return nil, fmt.Errorf("initialize store: %w", err)
	}
	defer store.Close()

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Create fallback lister (for full syncs when RSS has gaps)
	fallback := youtube.NewYtdlpLister()
	fallback.Path = cfg.YtdlpPath
	fallback.Timeout = cfg.YtdlpTimeout

	// Create sync manager
	rssLister := youtube.NewRSSLister()
	syncMgr := youtube.NewSyncManagerWithListers(rssLister, fallback, store)

	// Build list options
	listOpts := &youtube.ListOptions{
		MaxResults:  opts.MaxResults,
		ContentType: opts.ContentType,
	}

	// Perform sync
	result, err := syncMgr.SyncChannelVideos(ctx, channelURL, listOpts)
	if err != nil {
		return nil, fmt.Errorf("sync channel videos: %w", err)
	}

	// Convert to public result type
	return &SyncResult{
		Videos:         result.Videos,
		NewVideosCount: result.NewVideosCount,
		IsIncremental:  result.IsIncremental,
		IsFullSync:     result.IsFullSync,
		GapDetected:    result.GapDetected,
	}, nil
}

// SyncResult contains the outcome of a sync operation.
type SyncResult struct {
	// Videos is the list of videos discovered during this sync.
	Videos []youtube.VideoInfo
	// NewVideosCount is the number of new videos discovered.
	NewVideosCount int
	// IsIncremental is true if this was an incremental sync.
	IsIncremental bool
	// IsFullSync is true if this was a full sync.
	IsFullSync bool
	// GapDetected is true if RSS sync detected a gap in the feed.
	GapDetected bool
}

// DownloadOptions configures video download behavior.
type DownloadOptions struct {
	// OutputDir is the directory to save the downloaded video.
	// Defaults to current directory if empty.
	OutputDir string
	// Format specifies the video format: "best", "mp4", "webm", or a yt-dlp format string.
	// Defaults to "best" which selects the best quality up to 1080p.
	Format string
	// AudioOnly extracts audio as MP3 instead of downloading video.
	AudioOnly bool
	// AudioQuality specifies the audio quality in kbps when AudioOnly is true.
	// Defaults to 192 if not specified.
	AudioQuality int
	// IncludeMetadata saves video metadata to a JSON file alongside the video
	// by making a separate yt-dlp -J call and saving the result via Go.
	// This is distinct from WriteInfoJSON which uses yt-dlp's built-in metadata writing.
	IncludeMetadata bool
	// Filename specifies a custom output filename (without extension).
	// If empty, defaults to the sanitized video title.
	// When provided, this takes precedence over title-based naming.
	Filename string

	// Authentication and cookies
	// CookiesFile is the path to a Netscape-format cookies file.
	CookiesFile string
	// CookiesFromBrowser extracts cookies from a browser (e.g., 'chrome', 'firefox:profile-name').
	CookiesFromBrowser string
	// Username for authentication.
	Username string
	// Password for authentication.
	Password string
	// UseNetrc uses .netrc for authentication.
	UseNetrc bool
	// NetrcLocation specifies a custom .netrc file location.
	NetrcLocation string
	// VideoPassword for password-protected videos.
	VideoPassword string

	// Metadata and thumbnail options
	// WriteThumbnail writes the thumbnail image to a file.
	WriteThumbnail bool
	// EmbedMetadata embeds metadata (title, uploader, etc.) into the video file.
	EmbedMetadata bool
	// EmbedThumbnail embeds the thumbnail in the video file as cover art.
	EmbedThumbnail bool
	// EmbedChapters embeds chapter markers from the video description into the file.
	EmbedChapters bool
	// WriteInfoJSON writes video metadata to a .info.json file using yt-dlp's
	// built-in --write-info-json flag. This produces a more comprehensive metadata
	// file than IncludeMetadata (which uses a separate yt-dlp -J call).
	WriteInfoJSON bool
	// ConvertThumbnails converts thumbnails to the specified format (e.g., "jpg", "png").
	// Empty string means no conversion.
	ConvertThumbnails string

	// Download behavior options
	// Retries specifies the number of retries for failed downloads.
	Retries int
	// FragmentRetries specifies the number of retries for failed fragments.
	FragmentRetries int
	// NoOverwrites prevents overwriting existing files.
	NoOverwrites bool
	// Continue resumes partially downloaded files.
	Continue bool
	// RestrictFilenames restricts filenames to ASCII characters.
	RestrictFilenames bool
	// DownloadArchive specifies a file path for download archive tracking.
	DownloadArchive string
	// BreakOnExisting stops downloading when encountering already-downloaded videos.
	BreakOnExisting bool
	// MaxDownloads limits the number of videos to download.
	MaxDownloads int
	// ExtraArgs specifies additional yt-dlp arguments to append.
	ExtraArgs []string

	// Format selection and merging
	// FormatSort specifies the sort order for format selection.
	// Maps to --format-sort flag.
	FormatSort string
	// MergeOutputFormat specifies the container format for merged video+audio.
	// Maps to --merge-output-format flag (e.g., "mp4", "mkv", "webm").
	MergeOutputFormat string

	// Subtitle options
	// WriteSubtitles enables downloading subtitles.
	// Maps to --write-subs flag.
	WriteSubtitles bool
	// WriteAutoSubtitles enables downloading auto-generated subtitles.
	// Maps to --write-auto-subs flag.
	WriteAutoSubtitles bool
	// SubtitleLanguages specifies comma-separated subtitle languages to download.
	// Maps to --sub-langs flag (e.g., "en,es,fr").
	SubtitleLanguages string
	// SubtitleFormat specifies the subtitle format to download.
	// Maps to --sub-format flag (e.g., "srt", "vtt").
	SubtitleFormat string
	// ConvertSubtitles specifies the format to convert subtitles to.
	// Maps to --convert-subs flag (e.g., "srt", "vtt").
	ConvertSubtitles string
	// EmbedSubtitles enables embedding subtitles into the video file.
	// Maps to --embed-subs flag.
	EmbedSubtitles bool

	// Filtering and geo-restriction options
	// MatchFilters applies generic video filters (e.g., "like_count > 100").
	// Each entry results in a separate --match-filters flag.
	MatchFilters []string
	// DateAfter downloads only videos uploaded after this date (YYYYMMDD or relative like "now-1week").
	DateAfter string
	// DateBefore downloads only videos uploaded before this date (YYYYMMDD).
	DateBefore string
	// AgeLimit downloads only videos suitable for the given age.
	AgeLimit int
	// XForwardedFor uses the given country code or CIDR block for geo-restriction bypass.
	XForwardedFor string
	// PlaylistItems specifies which playlist items to download (e.g., "1-5,7,10-20").
	PlaylistItems string

	// Post-processing options
	// RemuxVideo remuxes the video into the specified container format (e.g., "mp4", "mkv").
	// Maps to --remux-video flag.
	RemuxVideo string
	// RecodeVideo re-encodes the video to the specified format (e.g., "mp4", "webm").
	// Maps to --recode-video flag.
	RecodeVideo string
	// SponsorBlockMark marks sponsor segments with chapter markers (comma-separated categories).
	// Maps to --sponsorblock-mark flag (e.g., "sponsor,intro,outro").
	SponsorBlockMark string
	// SponsorBlockRemove removes sponsor segments from the video (comma-separated categories).
	// Maps to --sponsorblock-remove flag (e.g., "sponsor,intro").
	SponsorBlockRemove string
	// FFmpegLocation specifies the path to ffmpeg/avconv binaries.
	// Maps to --ffmpeg-location flag.
	FFmpegLocation string
	// DownloadSections specifies time ranges to download (e.g., "*10:00-20:00").
	// Maps to --download-sections flag.
	DownloadSections string

	// Network options
	// Proxy specifies a proxy URL to use (e.g., "socks5://127.0.0.1:1080").
	// Maps to --proxy flag.
	Proxy string
	// RateLimit limits download rate in bytes per second (e.g., "50K", "4.2M").
	// Maps to --limit-rate flag.
	RateLimit string
	// SourceAddress specifies client-side IP address to bind to.
	// Maps to --source-address flag.
	SourceAddress string
	// ForceIPv4 forces all connections through IPv4.
	// Maps to --force-ipv4 flag.
	ForceIPv4 bool
	// SocketTimeout specifies socket timeout in seconds.
	// Maps to --socket-timeout flag.
	SocketTimeout int
	// ConcurrentFragments specifies number of fragments to download concurrently.
	// Maps to --concurrent-fragments flag.
	ConcurrentFragments int
	// Impersonate specifies a client to impersonate (e.g., 'chrome', 'firefox').
	// Maps to --impersonate flag.
	Impersonate string
}

// DownloadResult contains information about a completed download.
type DownloadResult struct {
	// VideoPath is the path to the downloaded video/audio file.
	VideoPath string
	// MetadataPath is the path to the metadata JSON file (if IncludeMetadata was true).
	MetadataPath string
	// Metadata contains the parsed video metadata (if IncludeMetadata was true).
	Metadata *youtube.VideoMetadata
}

// DownloadVideo downloads a YouTube video using default configuration.
// It uses yt-dlp to download the video in the best available quality up to 1080p.
//
// The videoID can be:
// - A video ID: dQw4w9WgXcQ
// - A full URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
//
// The video will be saved to the current directory with the video's title as filename.
func DownloadVideo(ctx context.Context, videoID string) (*DownloadResult, error) {
	return DownloadVideoWithOptions(ctx, videoID, &DownloadOptions{})
}

// DownloadVideoWithOptions downloads a YouTube video with custom options.
func DownloadVideoWithOptions(ctx context.Context, videoID string, opts *DownloadOptions) (*DownloadResult, error) {
	if opts == nil {
		opts = &DownloadOptions{}
	}

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Create downloader
	downloader := youtube.NewDownloader()
	downloader.YtdlpPath = cfg.YtdlpPath

	// Convert public options to internal options
	downloadOpts := &youtube.DownloadOptions{
		OutputDir:       opts.OutputDir,
		Format:          opts.Format,
		AudioOnly:       opts.AudioOnly,
		AudioQuality:    opts.AudioQuality,
		IncludeMetadata: opts.IncludeMetadata,
		Filename:        opts.Filename,
		YtdlpPath:       cfg.YtdlpPath,

		// Authentication and cookies
		CookiesFile:        opts.CookiesFile,
		CookiesFromBrowser: opts.CookiesFromBrowser,
		Username:           opts.Username,
		Password:           opts.Password,
		UseNetrc:           opts.UseNetrc,
		NetrcLocation:      opts.NetrcLocation,
		VideoPassword:      opts.VideoPassword,

		// Metadata and thumbnail options
		WriteThumbnail:    opts.WriteThumbnail,
		EmbedMetadata:     opts.EmbedMetadata,
		EmbedThumbnail:    opts.EmbedThumbnail,
		EmbedChapters:     opts.EmbedChapters,
		WriteInfoJSON:     opts.WriteInfoJSON,
		ConvertThumbnails: opts.ConvertThumbnails,

		// Download behavior options
		Retries:         opts.Retries,
		FragmentRetries: opts.FragmentRetries,
		NoOverwrites:    opts.NoOverwrites,
		Continue:        opts.Continue,
		RestrictFilenames: opts.RestrictFilenames,
		DownloadArchive: opts.DownloadArchive,
		BreakOnExisting: opts.BreakOnExisting,
		MaxDownloads:    opts.MaxDownloads,
		ExtraArgs:       opts.ExtraArgs,

		// Format selection and merging
		FormatSort:        opts.FormatSort,
		MergeOutputFormat: opts.MergeOutputFormat,

		// Subtitle options
		WriteSubtitles:     opts.WriteSubtitles,
		WriteAutoSubtitles: opts.WriteAutoSubtitles,
		SubtitleLanguages:  opts.SubtitleLanguages,
		SubtitleFormat:     opts.SubtitleFormat,
		ConvertSubtitles:   opts.ConvertSubtitles,
		EmbedSubtitles:     opts.EmbedSubtitles,

		// Filtering and geo-restriction options
		MatchFilters:  opts.MatchFilters,
		DateAfter:     opts.DateAfter,
		DateBefore:    opts.DateBefore,
		AgeLimit:      opts.AgeLimit,
		XForwardedFor: opts.XForwardedFor,
		PlaylistItems: opts.PlaylistItems,

		// Post-processing options
		RemuxVideo:         opts.RemuxVideo,
		RecodeVideo:        opts.RecodeVideo,
		SponsorBlockMark:   opts.SponsorBlockMark,
		SponsorBlockRemove: opts.SponsorBlockRemove,
		FFmpegLocation:     opts.FFmpegLocation,
		DownloadSections:   opts.DownloadSections,

		// Network options
		Proxy:               opts.Proxy,
		RateLimit:           opts.RateLimit,
		SourceAddress:       opts.SourceAddress,
		ForceIPv4:           opts.ForceIPv4,
		SocketTimeout:       opts.SocketTimeout,
		ConcurrentFragments: opts.ConcurrentFragments,
		Impersonate:         opts.Impersonate,
	}

	// Download video
	result, err := downloader.Download(ctx, videoID, downloadOpts)
	if err != nil {
		return nil, fmt.Errorf("download video: %w", err)
	}

	// Convert result to public type
	return &DownloadResult{
		VideoPath:    result.VideoPath,
		MetadataPath: result.MetadataPath,
		Metadata:     result.Metadata,
	}, nil
}

// ListFormats retrieves available video formats for a YouTube video.
func ListFormats(ctx context.Context, videoID string) ([]youtube.FormatInfo, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}
	return youtube.ListFormats(ctx, videoID, cfg.YtdlpPath)
}

// ListSubtitles retrieves available subtitle languages for a YouTube video.
func ListSubtitles(ctx context.Context, videoID string) ([]youtube.SubtitleInfo, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}
	return youtube.ListSubtitles(ctx, videoID, cfg.YtdlpPath)
}
