// Package ytsync provides a high-level API for YouTube video synchronization.
//
// This package offers convenience functions for the most common operations:
// listing videos, downloading videos, and extracting transcripts.
//
// Example usage:
//
//	ctx := context.Background()
//	videos, err := ytsync.ListVideos(ctx, "https://www.youtube.com/channel/UCxxxxx")
//	if err != nil {
//		log.Fatal(err)
//	}
//	for _, v := range videos {
//		fmt.Println(v.Title)
//	}
package ytsync

import (
	"context"
	"fmt"
	"ytsync/config"
	"ytsync/youtube"
)

// ListVideos retrieves videos from a YouTube channel using default configuration.
// It uses the RSS feed by default for fast listing of recent videos.
//
// The channelURL can be:
// - A channel URL: https://www.youtube.com/channel/UCxxxxx
// - A handle: https://www.youtube.com/@channelname
// - A channel ID: UCxxxxx
//
// For full history of all videos, use ListVideosWithOptions with a Ytdlp lister.
func ListVideos(ctx context.Context, channelURL string) ([]youtube.VideoInfo, error) {
	return ListVideosWithOptions(ctx, channelURL, &ListOptions{})
}

// ListOptions configures video listing behavior.
type ListOptions struct {
	// MaxResults limits the number of videos to retrieve (0 = all available)
	MaxResults int
	// UseRSS forces using RSS feed instead of yt-dlp (default: true for efficiency)
	UseRSS bool
	// ContentType specifies what to list: videos, streams, or both (default: videos)
	ContentType youtube.ContentType
}

// ListVideosWithOptions retrieves videos with custom options.
func ListVideosWithOptions(ctx context.Context, channelURL string, opts *ListOptions) ([]youtube.VideoInfo, error) {
	if opts == nil {
		opts = &ListOptions{}
	}

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Create lister
	var lister youtube.VideoLister
	if opts.UseRSS {
		lister = youtube.NewRSSLister()
	} else {
		ytdlp := youtube.NewYtdlpLister()
		ytdlp.Path = cfg.YtdlpPath
		ytdlp.Timeout = cfg.YtdlpTimeout
		lister = ytdlp
	}

	// Build list options
	listOpts := &youtube.ListOptions{
		MaxResults:  opts.MaxResults,
		ContentType: opts.ContentType,
	}

	// List videos
	videos, err := lister.ListVideos(ctx, channelURL, listOpts)
	if err != nil {
		return nil, fmt.Errorf("list videos: %w", err)
	}

	return videos, nil
}

// TranscriptOptions configures transcript extraction.
type TranscriptOptions struct {
	// Languages specifies preferred language codes (e.g., ["en", "es"]).
	// Empty means try all available languages.
	Languages []string
	// SkipAutoGenerated skips auto-generated captions if true.
	SkipAutoGenerated bool
}

// ExtractTranscript retrieves and parses the transcript for a video.
// It returns the first available transcript matching the options.
func ExtractTranscript(ctx context.Context, videoID string) (*youtube.Transcript, error) {
	return ExtractTranscriptWithOptions(ctx, videoID, &TranscriptOptions{})
}

// ExtractTranscriptWithOptions extracts a transcript with custom options.
func ExtractTranscriptWithOptions(ctx context.Context, videoID string, opts *TranscriptOptions) (*youtube.Transcript, error) {
	if opts == nil {
		opts = &TranscriptOptions{}
	}

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Create extractor
	extractor := youtube.NewTranscriptExtractor()
	extractor.YtdlpPath = cfg.YtdlpPath
	extractor.Timeout = cfg.YtdlpTimeout

	// Build extract options
	extractOpts := &youtube.ExtractOptions{
		Languages:         opts.Languages,
		Format:            "json3",
		SkipAutoGenerated: opts.SkipAutoGenerated,
	}

	// Extract transcript
	transcript, err := extractor.Extract(ctx, videoID, extractOpts)
	if err != nil {
		return nil, fmt.Errorf("extract transcript: %w", err)
	}

	return transcript, nil
}

// FetchVideoMetadata retrieves comprehensive metadata for a video using yt-dlp.
// This includes title, description, duration, view count, and other details.
func FetchVideoMetadata(ctx context.Context, videoID string) (*youtube.VideoMetadata, error) {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}

	// Fetch metadata
	metadata, err := youtube.FetchMetadata(ctx, videoID, cfg.YtdlpPath)
	if err != nil {
		return nil, fmt.Errorf("fetch metadata: %w", err)
	}

	return metadata, nil
}
